"""empty message

Revision ID: 1e6cd96c5490
Revises: 1ee58dd0cfd8
Create Date: 2016-03-18 11:16:49.600949

"""

# revision identifiers, used by Alembic.
revision = '1e6cd96c5490'
down_revision = '1ee58dd0cfd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
