"""empty message

Revision ID: 1ee58dd0cfd8
Revises: 2c4cc7546e1c
Create Date: 2016-03-17 03:13:43.004077

"""

# revision identifiers, used by Alembic.
revision = '1ee58dd0cfd8'
down_revision = '2c4cc7546e1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    ### end Alembic commands ###
