"""empty message

Revision ID: 2c4cc7546e1c
Revises: None
Create Date: 2016-03-17 00:02:21.888769

"""

# revision identifiers, used by Alembic.
revision = '2c4cc7546e1c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True),
    sa.Column('ideal', sa.String(length=1000), nullable=True),
    sa.Column('non_ideal', sa.String(length=1000), nullable=True),
    sa.Column('introduce', sa.String(length=1000), nullable=True),
    sa.Column('interest', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.String(length=255), nullable=True),
    sa.Column('friend', sa.String(length=10), nullable=True),
    sa.Column('prefer_age', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
